version: '3'
services:
  minecraft-server:
    build: .
    image: purpur-minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./plugins:/minecraft-server/plugins
    environment:
      EULA: "true"
